# Generated by Django 3.2.4 on 2021-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anish_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=20000, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20000, unique=True),
        ),
    ]
